name: Run Tests
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
env:
  JULIA_NUM_THREADS: 2
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        julia-version: ['1', 'nightly']
        julia-arch: [x64, x86]
    steps:
      - uses: actions/checkout@v2
      - uses: julia-actions/setup-julia@v1
        with:
          version: ${{ matrix.julia-version }}
      - uses: julia-actions/julia-runtest@v1.5.1
        with:
          inline: yes
          coverage: true
          depwarn: yes
          project: .
